[package]
name = "backfill-thumbnails"
version = "0.1.0"
edition = "2021"
readme = "README.md"

[lib]
name = "backfill_thumbnails"
path = "src/lib.rs"

[[bin]]
name = "backfill-thumbnails"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.97"
chrono = "0.4"
clap = { version = "4.5.31", features = ["derive"] }
image = { version = "0.25.6", default-features = false, features = ["png"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
storj-interface = { path = "../.." }
tempfile = "3"
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
